# Generated by Django 5.2 on 2025-04-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='valor_inicial',
        ),
    ]
