# Generated by Django 5.2 on 2025-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_remove_orcamento_valor_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
