# Generated by Django 5.2 on 2025-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_pagamento_valor_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='valor_inicial',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
